### PR TITLE
fix: extension action 'context' category 

### LINKED ISSUE #2256: Extension actions with category 'actions' appear in both "Open with..." dropdown and standalone context menu
### Initial Checklist

- [x] I understand this is a bug report and questions should be posted in the [Community Discussions](https://github.com/orgs/opencloud-eu/discussions/)
- [x] I searched [issues](https://github.com/opencloud-eu/web/issues?q=is%3Aissue) and couldn’t find anything (or linked relevant results below)

#### Description

Since commit https://github.com/opencloud-eu/web/commit/3b48960533 ("feat: remove default-actions extension point"), extensions registered on `global.files.context-actions` with `category: 'actions'` appear **twice** in the context menu:

1. Inside the **"Open with..."** dropdown (via `getAllOpenWithActions`)
2. In the **standalone actions section** (via `menuItemsActions`)

Additionally, if no editor app claims priority for a file type, the extension action becomes the **default action** on file click, because `extensionsContextActions` is spread before `editorActions` in `getAllOpenWithActions`.

#### Root Cause

In `packages/web-pkg/src/composables/actions/files/useFileActions.ts`, `extensionsContextActions` includes actions with `category === 'actions'` (line 105):

https://github.com/opencloud-eu/web/blob/c05b9cd6caf2a03f21a14aba4e51a2f00adc8658/packages/web-pkg/src/composables/actions/files/useFileActions.ts#L103-L105

This computed is then used unfiltered in `getAllOpenWithActions` (line 276–279):

https://github.com/opencloud-eu/web/blob/c05b9cd6caf2a03f21a14aba4e51a2f00adc8658/packages/web-pkg/src/composables/actions/files/useFileActions.ts#L276-L280

```ts
  ...unref(extensionsContextActions),  // includes category 'actions'
```

Before `3b48960533`, `category === 'actions'` extensions were appended at the **end** of `getAllOpenWithActions` (after editors), and `menuItemsContextDrop` had a separate `category === 'context'` filter. Both safeguards were removed.

#### Suggested Fix

Filter `extensionsContextActions` in `getAllOpenWithActions` to only include actions meant for the "Open with..." dropdown (`category === 'context'` or no category). Actions with `category === 'actions'` should only appear in `menuItemsActions`.

```diff
diff --git a/packages/web-pkg/src/composables/actions/files/useFileActions.ts b/packages/web-pkg/src/composables/actions/files/useFileActions.ts
index e9e196ca2e..a1b2c3d4e5 100644
--- a/packages/web-pkg/src/composables/actions/files/useFileActions.ts
+++ b/packages/web-pkg/src/composables/actions/files/useFileActions.ts
@@ -273,7 +273,9 @@ export const useFileActions = () => {
     const filterCallback = (action: FileAction) => action.isVisible(options)
 
     const primaryActions = [
-      ...unref(extensionsContextActions),
+      ...unref(extensionsContextActions).filter(
+        (a) => isNil(a.category) || a.category === 'context'
+      ),
       ...unref(editorActions),
       ...unref(navigateActions)
     ]
```

This ensures:
- `category === 'context'` (or no category) → appears in "Open with..." dropdown 
- `category === 'actions'` → appears only in standalone actions section 
- Editor actions remain first in `getAllOpenWithActions` priority after extension `context` actions, preserving expected default-action behavior 

#### Affected Version

Introduced in `3b48960533` ("feat: remove default-actions extension point")

#### Steps to Reproduce

Register a minimal extension app with an action on `global.files.context-actions` using `category: 'actions'`:

```ts
// src/index.ts
import {
  ApplicationSetupOptions,
  ActionExtension
} from '@opencloud-eu/web-pkg'
import { computed } from 'vue'

export default {
  setup({ applicationConfig }: ApplicationSetupOptions) {
    const extensions = computed<ActionExtension[]>(() => [
      {
        id: 'com.example.my-action',
        type: 'action',
        extensionPointIds: ['global.files.context-actions'],
        action: {
          name: 'my-action',
          icon: 'mail',
          category: 'actions',
          label: () => 'My Custom Action',
          isVisible: () => true,
          handler: (options) => {
            const resources = options?.resources ?? []
            console.log('Action triggered on:', resources)
          }
        }
      }
    ])

    return {
      appInfo: {
        id: 'my-action-app',
        name: 'My Action App',
        icon: 'mail',
        color: '#0D856F'
      },
      extensions
    }
  }
}
```

### Expected Outcome

**Expected behavior:**
- "My Custom Action" appears **only** in the standalone actions section of the context menu
- Clicking a file opens the preview/editor as the default action

Image

### Actual Outcome

**Actual behavior:**
- "My Custom Action" appears **twice**: inside the "Open with..." dropdown AND in the standalone actions section
- Clicking a file triggers "My Custom Action" instead of the preview/editor, because `extensionsContextActions` is spread before `editorActions` in `getAllOpenWithActions`

Image

### PR DESCRIPTION
**Pull request by JammingBen**
Makes sure that extension actions of category `context` are the only actions that get used for the "Open with" menu while also being candidates for default actions.

This prevents certain actions from showing up multiple times in the context menu.

fixes https://github.com/opencloud-eu/web/issues/2256

### CODE REVIEW

File: packages/web-pkg/src/composables/actions/files/useFileActions.ts [hunk 1]
```diff
@@ -100,10 +99,7 @@ export const useFileActions = () => {
       }) || []
     )
       .map((e) => e.action)
-      .filter(
-        (action) =>
-          isNil(action.category) || action.category === 'context' || action.category === 'actions'
-      )
```
Comment (JammingBen) [inline packages/web-pkg/src/composables/actions/files/useFileActions.ts:106]: @kulmann Do you remember why you added the filter for `isNil` and `category === 'actions'` for `extensionsContextActions` in https://github.com/opencloud-eu/web/commit/3b489605338a9ad7d1c24449f9a2821c645e0738? It doesn't look right to me, and I couldn't detect any fallout from removing those.

File: packages/web-pkg/src/composables/actions/types.ts [hunk 2]
```diff
@@ -2,43 +2,122 @@ import { Resource, SpaceResource } from '@opencloud-eu/web-client'
...
+   *
+   * - actions: action will appear in the "actions" section of the resource context menu.
+   * - context: action will appear in the "Open with..."-menu of the resource context menu.
+   *   It will also be the default when no other action is available for the given file type.
+   * - share: action will appear in the "shares" section of the resource context menu.
+   * - sidebar: action will appear in the "sidebar" section of the resource context menu.
+   *
+   * @default actions
+   */
+  category?: ActionCategory
```
Comment (JammingBen) [inline packages/web-pkg/src/composables/actions/types.ts:32]: I don't now what we were thinking when naming these, but it's super confusing to me. I hope this comment brings at least some clarity to devs using this interface.

File: packages/web-pkg/src/composables/actions/files/useFileActions.ts (hunk 1 above)
Comment (kulmann) [reply packages/web-pkg/src/composables/actions/files/useFileActions.ts:106]: no clue 😅  should be fine like you have it now.

**Review by kulmann — APPROVED** [review]
