### PR TITLE
fix: embed mode allows to choose locations that are not accessible

### LINKED ISSUE #613: Locations without current folder can be selected for "Save as"
### Initial Checklist

- [x] I understand this is a bug report and questions should be posted in the [Community Discussions](https://github.com/orgs/opencloud-eu/discussions/)
- [x] I searched [issues](https://github.com/opencloud-eu/web/issues?q=is%3Aissue) and couldn’t find anything (or linked relevant results below)

### Bug Description

Locations without current folder (e.g. Shared with me page) can be selected for the "Save as" action.

### Reproduction Steps

* create a new text file
* open the text file
* click "Save As" via the context menu in the top app bar
* navigate to e.g. the Shared with Me page
* click on "Choose" on the bottom right

### Expected Outcome

An error occurs since the file can't be created under this location.

### Actual Outcome

Disable the action if no current folder is available or if the user doesn't have write permissions in it.

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #613 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bugfix
- [ ] Enhancement (a change that doesn't break existing code or deployments)
- [ ] Breaking change (a modification that affects current functionality)
- [ ] Technical debt (addressing code that needs refactoring or improvements)
- [ ] Tests (adding or improving tests)
- [ ] Documentation (updates or additions to documentation)
- [ ] Maintenance (like dependency updates or tooling adjustments)

### CODE REVIEW

**Comment by AlexAndBear** [comment]
@kulmann I did refactor a little, because it was quite hard to understand which button is rendered when, and if the button is disabled or not

File: packages/web-app-files/src/components/EmbedActions/EmbedActions.vue [hunk 1]
```diff
@@ -24,23 +24,31 @@
...
-      <oc-button
-        v-if="!isFilePicker"
-        data-testid="button-select"
-        appearance="filled"
-        :disabled="areSelectActionsDisabled"
-        @click="emitSelect"
-      >
-        {{ selectLabel }}
-      </oc-button>
+      <div v-if="!isFilePicker">
```
Comment (kulmann) [inline packages/web-app-files/src/components/EmbedActions/EmbedActions.vue]:
```suggestion
      <template v-if="!isFilePicker">
```

File: packages/web-app-files/src/components/EmbedActions/EmbedActions.vue [hunk 2]
```diff
@@ -24,23 +24,31 @@
...
+        <oc-button
+          v-else
+          data-testid="button-select"
+          appearance="filled"
+          :disabled="isAttachAsCopyButtonDisabled"
+          @click="emitSelect"
+        >
+          {{ $gettext('Attach as copy') }}
+        </oc-button>
+      </div>
```
Comment (kulmann) [inline packages/web-app-files/src/components/EmbedActions/EmbedActions.vue]:
```suggestion
      </template>
```

**Review by kulmann — APPROVED** [review]

**Comment by AlexAndBear** [comment]
follow up: add some unit tests
