### PR TITLE
fix: status column appears multiple times

### LINKED ISSUE #801: Two "status" columns in space listing
### Initial Checklist

- [x] I understand this is a bug report and questions should be posted in the [Community Discussions](https://github.com/orgs/opencloud-eu/discussions/)
- [x] I searched [issues](https://github.com/opencloud-eu/web/issues?q=is%3Aissue) and couldn’t find anything (or linked relevant results below)

### Bug Description

With the latest code from web I get two "Status" columns in the space list

Image

### Reproduction Steps

Click on "Spaces" in the files app

### Expected Outcome

No duplicated columns

### Actual Outcome

duplicated columns

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #801 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bugfix
- [ ] Enhancement (a change that doesn't break existing code or deployments)
- [ ] Breaking change (a modification that affects current functionality)
- [ ] Technical debt (addressing code that needs refactoring or improvements)
- [ ] Tests (adding or improving tests)
- [ ] Documentation (updates or additions to documentation)
- [ ] Maintenance (like dependency updates or tooling adjustments)

### CODE REVIEW

File: packages/web-pkg/src/helpers/statusIndicators.ts [hunk 1]
```diff
@@ -115,6 +115,30 @@ const getProcessingIndicator = ({ resource }: { resource: Resource }): ResourceI
...
+}
+
+const getSpaceDisabledIndicator = ({ resource }: { resource: Resource }): ResourceIndicator => {
+  return {
+    id: `resource-space-disabled-${resource.getDomSelector()}`,
+    accessibleDescription: $gettext('Space is disabled'),
+    label: $gettext('This space is disabled'),
+    icon: 'stop-circle',
+    category: 'system',
+    type: 'resource-space-enabled',
```
Comment (AlexAndBear) [inline packages/web-pkg/src/helpers/statusIndicators.ts]:
```suggestion
    type: 'resource-space-disabled',
```

Comment (AlexAndBear) [reply packages/web-pkg/src/helpers/statusIndicators.ts]: @kulmann is the type correct? This space is disabled but maybe the context ("it's about enabled spaces") is correct?

**Comment by AlexAndBear** [comment]
successor of https://github.com/opencloud-eu/web/pull/803

File: packages/web-pkg/src/helpers/statusIndicators.ts (hunk 1 above)
Comment (kulmann) [reply packages/web-pkg/src/helpers/statusIndicators.ts]: Should be `disabled`, because it's not a broad category but more like an extension-id (= unique for the indicator, but multiple can exist for the multiple rows of the table). I get the feeling that we should move back to the extension system with the indicators.

**Review by kulmann — APPROVED** [review]
thank you for the cleanup 💪
