### PR TITLE
fix: sorting of spaces is faulty when space names contain numbers

### LINKED ISSUE #2430: Numeric ordering is wrong
## Describe the bug
I have some spaces which only contain digits in the name. Ordering is set to A-Z. The spaces are not ordered correctly. (See screenshot below):

Image

## Expected behavior
Folders in spaces are ordered correct:

Image

Image

Spaces should be ordered the same.

## Setup
OpenCloud 6.1.0 rolling

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes opencloud-eu/web#2430 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bugfix
- [ ] Enhancement (a change that doesn't break existing code or deployments)
- [ ] Breaking change (a modification that affects current functionality)
- [ ] Technical debt (addressing code that needs refactoring or improvements)
- [ ] Tests (adding or improving tests)
- [ ] Documentation (updates or additions to documentation)
- [ ] Maintenance (like dependency updates or tooling adjustments)

### CODE REVIEW

File: packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue [hunk 1]
```diff
@@ -78,23 +78,20 @@
     <template #totalQuota="{ item }"> {{ getTotalQuota(item) }}</template>
     <template #usedQuota="{ item }"> {{ getUsedQuota(item) }}</template>
     <template #remainingQuota="{ item }"> {{ getRemainingQuota(item) }}</template>
+    <template #indicators="{ item }">
+      <oc-status-indicators
+        v-if="getIndicators({ space: item, resource: item }).length > 0"
```
Comment (AlexAndBear) [inline packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue]:
```suggestion

```

**Review by kulmann — COMMENTED** [review]
When I sort by some criterion OTHER than the space name, the sorting falls back to the pure lexicographical sorting. See screenshot.

Image


Edit: thanks for the hint: Together with the backend changes in https://github.com/opencloud-eu/opencloud/pull/2657 the behaviour is correct. 🥳

**Review by kulmann — APPROVED** [review]
Needs linting fixes, but otherwise works great 🥳
